### ISSUE TITLE
Choose gh-pages and master branch

### ISSUE THREAD

**Issue by opnay** [maxheld83/ghpages#3]
Github can choose `gh-pages` and `master` branch for publishing github pages in **non** `username.github.io` repository.

I want to push master branch on repository that selected `master` branch to publish github pages.
but, `ghpages` action couldn't choose branch.

Can you update for it?

**Comment by maxheld83** [comment]
ah I see – I didn't know this was possible, but you're right @opnay the [docs says so](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/). 

I guess this could be done, though I'm a little skeptical because of the tradeoff between complexity and reward.
Is there a pressing reason why you'd want to deploy to `master` on *non* `username.github.io` repos?

I think to offer this, we'd need to:

- [ ] set a `NULL` default, by which the action would choose automatically (as it currently does).
- [ ] make sure that the deploy branch *is not the same as the source* branch (because this could get ugly, as per #4).
- [ ] anything else I might have forgotten?

**Comment by maxheld83** [comment]
ok, I researched this some more.
As I mentioned above, I think we'd need to make sure that the deploy branch is not the *same* as the source branch.
That *could* be tested in bash, but we'd need to know the branch that we (= the action) is currently running on.

Turns out, that's not super straightforward.

GitHub exposes the [`GITHUB_REF`](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#environment-variables) environment variable to the action, which can be:

> The branch or tag ref that triggered the workflow. For example, `refs/heads/feature-branch-1`. 
> If neither a branch or tag is available for the event type, the variable will not exist.

This is already a problem, because in the case of a tag, we don't really know which branch that is.

But it gets worse: depending on how the action is triggered, the `GITHUB_REF` may not be set at all.
Would be alright for `push`, which is probably the most commonly used trigger, but users *may* want to use this action on other triggers, in which case there might be no `GITHUB_REF`, and by extension, no way of knowing (AFAIK?) of which branch we're currently on, and thus no way to avoid a massive merge conflict.

These complexities and caveats seem a little too much for me as of now, and I think the costs of confusing users and causing unintended, hard-to-reason-about problems is too high for the relatively small gain.

After all, you can just set your *non* `username.github.io` repo to publish from `gh-pages` and be done with it.

This is also, I think how it was historically.

So I'm going to close this as `wont fix`.

If you see changes in this field or options/arguments I have forgotten about, feel free to reopen or comment @opnay.
